# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omnimapper_msgs/PoseFactorGraphNode.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import omnimapper_msgs.msg
import geometry_msgs.msg

class PoseFactorGraphNode(genpy.Message):
  _md5sum = "f7ee085aab2c2010a0bf7e87f19392d1"
  _type = "omnimapper_msgs/PoseFactorGraphNode"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """GtsamSymbol[] syms
geometry_msgs/PoseWithCovariance measurement

================================================================================
MSG: omnimapper_msgs/GtsamSymbol
uint8 symbol
uint64 index

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['syms','measurement']
  _slot_types = ['omnimapper_msgs/GtsamSymbol[]','geometry_msgs/PoseWithCovariance']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       syms,measurement

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseFactorGraphNode, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.syms is None:
        self.syms = []
      if self.measurement is None:
        self.measurement = geometry_msgs.msg.PoseWithCovariance()
    else:
      self.syms = []
      self.measurement = geometry_msgs.msg.PoseWithCovariance()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.syms)
      buff.write(_struct_I.pack(length))
      for val1 in self.syms:
        _x = val1
        buff.write(_get_struct_BQ().pack(_x.symbol, _x.index))
      _x = self
      buff.write(_get_struct_7d().pack(_x.measurement.pose.position.x, _x.measurement.pose.position.y, _x.measurement.pose.position.z, _x.measurement.pose.orientation.x, _x.measurement.pose.orientation.y, _x.measurement.pose.orientation.z, _x.measurement.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.measurement.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.syms is None:
        self.syms = None
      if self.measurement is None:
        self.measurement = geometry_msgs.msg.PoseWithCovariance()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.syms = []
      for i in range(0, length):
        val1 = omnimapper_msgs.msg.GtsamSymbol()
        _x = val1
        start = end
        end += 9
        (_x.symbol, _x.index,) = _get_struct_BQ().unpack(str[start:end])
        self.syms.append(val1)
      _x = self
      start = end
      end += 56
      (_x.measurement.pose.position.x, _x.measurement.pose.position.y, _x.measurement.pose.position.z, _x.measurement.pose.orientation.x, _x.measurement.pose.orientation.y, _x.measurement.pose.orientation.z, _x.measurement.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.measurement.covariance = _get_struct_36d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.syms)
      buff.write(_struct_I.pack(length))
      for val1 in self.syms:
        _x = val1
        buff.write(_get_struct_BQ().pack(_x.symbol, _x.index))
      _x = self
      buff.write(_get_struct_7d().pack(_x.measurement.pose.position.x, _x.measurement.pose.position.y, _x.measurement.pose.position.z, _x.measurement.pose.orientation.x, _x.measurement.pose.orientation.y, _x.measurement.pose.orientation.z, _x.measurement.pose.orientation.w))
      buff.write(self.measurement.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.syms is None:
        self.syms = None
      if self.measurement is None:
        self.measurement = geometry_msgs.msg.PoseWithCovariance()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.syms = []
      for i in range(0, length):
        val1 = omnimapper_msgs.msg.GtsamSymbol()
        _x = val1
        start = end
        end += 9
        (_x.symbol, _x.index,) = _get_struct_BQ().unpack(str[start:end])
        self.syms.append(val1)
      _x = self
      start = end
      end += 56
      (_x.measurement.pose.position.x, _x.measurement.pose.position.y, _x.measurement.pose.position.z, _x.measurement.pose.orientation.x, _x.measurement.pose.orientation.y, _x.measurement.pose.orientation.z, _x.measurement.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.measurement.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_BQ = None
def _get_struct_BQ():
    global _struct_BQ
    if _struct_BQ is None:
        _struct_BQ = struct.Struct("<BQ")
    return _struct_BQ
