# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from omnimapper_msgs/TestGaussianRegions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import omnimapper_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class TestGaussianRegions(genpy.Message):
  _md5sum = "910f257b519d3a8b06fa080a0a118014"
  _type = "omnimapper_msgs/TestGaussianRegions"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/TransformStamped odom_pose
omnimapper_msgs/GaussianRegion region


================================================================================
MSG: geometry_msgs/TransformStamped
# This expresses a transform from coordinate frame header.frame_id
# to the coordinate frame child_frame_id
#
# This message is mostly used by the 
# <a href="http://wiki.ros.org/tf">tf</a> package. 
# See its documentation for more information.

Header header
string child_frame_id # the frame id of the child frame
Transform transform

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: omnimapper_msgs/GaussianRegion
std_msgs/Header header
#represents a whatever from the gaussian region detector
float64 x
float64 y
float64[4] covariance
"""
  __slots__ = ['odom_pose','region']
  _slot_types = ['geometry_msgs/TransformStamped','omnimapper_msgs/GaussianRegion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       odom_pose,region

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TestGaussianRegions, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.odom_pose is None:
        self.odom_pose = geometry_msgs.msg.TransformStamped()
      if self.region is None:
        self.region = omnimapper_msgs.msg.GaussianRegion()
    else:
      self.odom_pose = geometry_msgs.msg.TransformStamped()
      self.region = omnimapper_msgs.msg.GaussianRegion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.odom_pose.header.seq, _x.odom_pose.header.stamp.secs, _x.odom_pose.header.stamp.nsecs))
      _x = self.odom_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.odom_pose.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.odom_pose.transform.translation.x, _x.odom_pose.transform.translation.y, _x.odom_pose.transform.translation.z, _x.odom_pose.transform.rotation.x, _x.odom_pose.transform.rotation.y, _x.odom_pose.transform.rotation.z, _x.odom_pose.transform.rotation.w, _x.region.header.seq, _x.region.header.stamp.secs, _x.region.header.stamp.nsecs))
      _x = self.region.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2d().pack(_x.region.x, _x.region.y))
      buff.write(_get_struct_4d().pack(*self.region.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.odom_pose is None:
        self.odom_pose = geometry_msgs.msg.TransformStamped()
      if self.region is None:
        self.region = omnimapper_msgs.msg.GaussianRegion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.odom_pose.header.seq, _x.odom_pose.header.stamp.secs, _x.odom_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odom_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.odom_pose.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odom_pose.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.odom_pose.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.odom_pose.transform.translation.x, _x.odom_pose.transform.translation.y, _x.odom_pose.transform.translation.z, _x.odom_pose.transform.rotation.x, _x.odom_pose.transform.rotation.y, _x.odom_pose.transform.rotation.z, _x.odom_pose.transform.rotation.w, _x.region.header.seq, _x.region.header.stamp.secs, _x.region.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.region.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.region.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.region.x, _x.region.y,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 32
      self.region.covariance = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.odom_pose.header.seq, _x.odom_pose.header.stamp.secs, _x.odom_pose.header.stamp.nsecs))
      _x = self.odom_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.odom_pose.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.odom_pose.transform.translation.x, _x.odom_pose.transform.translation.y, _x.odom_pose.transform.translation.z, _x.odom_pose.transform.rotation.x, _x.odom_pose.transform.rotation.y, _x.odom_pose.transform.rotation.z, _x.odom_pose.transform.rotation.w, _x.region.header.seq, _x.region.header.stamp.secs, _x.region.header.stamp.nsecs))
      _x = self.region.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2d().pack(_x.region.x, _x.region.y))
      buff.write(self.region.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.odom_pose is None:
        self.odom_pose = geometry_msgs.msg.TransformStamped()
      if self.region is None:
        self.region = omnimapper_msgs.msg.GaussianRegion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.odom_pose.header.seq, _x.odom_pose.header.stamp.secs, _x.odom_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odom_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.odom_pose.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.odom_pose.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.odom_pose.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.odom_pose.transform.translation.x, _x.odom_pose.transform.translation.y, _x.odom_pose.transform.translation.z, _x.odom_pose.transform.rotation.x, _x.odom_pose.transform.rotation.y, _x.odom_pose.transform.rotation.z, _x.odom_pose.transform.rotation.w, _x.region.header.seq, _x.region.header.stamp.secs, _x.region.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.region.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.region.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.region.x, _x.region.y,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 32
      self.region.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
