apiVersion: batch/v1
kind: Job
metadata:
  name: generative-inpainting-train
spec:
  backoffLimit: 1
  template:
    spec:
      volumes:
      - name: rook-cephfs-erl-ucsd-vdhiman
        persistentVolumeClaim:
          claimName:  rook-cephfs-erl-ucsd-vdhiman
      containers:
      - name: tensorflow
        #image: tensorflow/tensorflow:1.14.0-gpu-py3-jupyter
        #image: gitlab-registry.nautilus.optiputer.net/vdhiman/generative_inpainting:latest
        image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
        command:
          - "bash"
          - "-c"
          - "export CODE_DIR=/home/vdhiman/wrk/generative_inpainting DATA_ROOT=/home/vdhiman/wrk/generative_inpainting && cd $CODE_DIR && pip install -r requirements.txt && python train.py"
        volumeMounts:
        - name: rook-cephfs-erl-ucsd-vdhiman
          mountPath: /home/vdhiman
        resources:
          limits:
            memory: 32Gi
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: 32Gi
            cpu: "8"
            nvidia.com/gpu: "2"
      restartPolicy: Never
