apiVersion: v1
kind: Pod
metadata:
  name: tf-sess
spec:
  volumes:
  - name: rook-cephfs-erl-ucsd-vdhiman
    persistentVolumeClaim:
      claimName:  rook-cephfs-erl-ucsd-vdhiman
  containers:
  - name: tensorflow
    #image: tensorflow/tensorflow:1.14.0-gpu-py3-jupyter
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: rook-cephfs-erl-ucsd-vdhiman
      mountPath: /home/vdhiman
    resources:
      limits:
        nvidia.com/gpu: "1"
