version: "2.4"
services:
  ros_nvidia:
    image: ros-melodic-bionic-nvidia
    build:
      context: .
      dockerfile: Dockerfile_ros_nvidia

  core:
    image: ros-melodic-bionic-nvidia
    command: ["roscore"]
    network_mode: host
    
  predictor:
    build:
      context: .
    image: generative_inpainting_ros
    environment:
      - DISPLAY
      - TERM
      - ROS_NAMESPACE=robot0
    entrypoint: ["/ros_entrypoint.sh"]
    command: ["bash", "-c", "pip3 install --upgrade numpy pillow && python3 ros/map_predictor.py"]
    network_mode: host
    volumes:
      - $HOME:$HOME
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia

    depends_on: [core]

    #rosbag:
    #roimage: generative_inpainting_ros
    #rocommand: ["rosbag", "play", "/home/vdhiman/aux/generative_inpainting/data/radish/maps_pgm/department_diiga__2019-11-13-01-05-46.bag", "/robot0/gmapping_map:=/robot0/point_cloud_cache/renderer/full_map" ]
    #ronetwork_mode: host
    #rovolumes:
    #ro  - $HOME:$HOME
    #ro  - /tmp/.X11-unix:/tmp/.X11-unix
    #roruntime: nvidia
    #rodepends_on: [core]


